version: '3'
services:

  java-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 9290:9290
    environment:
      - MYSQL_HOST=database
  database:
    image: library/mysql:latest
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ip-tracer
      MYSQL_DATABASE: ip-tracer